---

- name: "Ensure gunicorn is installed"
  pip: virtualenv="{{ application_venv }}" name=gunicorn

- name: "Create the gunicorn run folder for process management"
  file: path="{{ application_path }}/shared/run" state=directory mode=0755

- name: "Create the gunicorn script file"
  template: src=gunicorn_start.j2 dest="{{ application_venv }}/bin/gunicorn_start" mode=0755
